service:
  name: anyserver-dev
  host: 127.0.0.1
  port: 33100
packet:
  filename: ./sendlist.txt
  wait: 5000
archive:
  filename: ./archive.csv
  type: cvs
logging:
  filename: ./anyserver.log
  timestamp: 2006-01-02 15:04:05.000


