service:
  name: anyclient-dev-tx
  host: 127.0.0.1
  port: 32100
packet:
  use: true
  filename: ./sendlist.txt
  wait: 5000
archive:
  use: true
  filename: ./archive.csv
  type: cvs
logging:
  filename: ./anyclient.log
  timestamp: 2006-01-02 15:04:05.000

