service:
  name: pktservice
  network:
    - channel:
        name: Service1
        type: TC
        recon_interval: 1000
        listener: 
          name: ServerSrv1
          host: 127.0.0.1
          port: 32100
        dialer:
          name: ClientSrv1
          host: 127.0.0.1
          port: 33100    
          retry: 10
    - channel:
        name: Service2
        type: TM
        recon_interval: 1000
        listener: 
          name: ServerSrv2
          host: 127.0.0.1
          port: 32200
        dialer:
          name: ClientSrv2
          host: 127.0.0.1
          port: 33200    
          retry: 10
packet:
  use: false
  filename: ./sendlist.txt
  wait: 5000
archive:
  use: true
  filename: ./archive.csv
  type: cvs
logging:
  filename: ./pktservice.log
  timestamp: 2006-01-02 15:04:05.000


