service:
  name: pktservice
  connections:
    listeners: 
      - name: ServerSrv1
        addr: 127.0.0.1
        port: 32100
    dialers:
      - name: ClientSrv1
        addr: 127.0.0.1
        port: 33100    
packet:
  filename: ./sendlist.txt
  wait: 5000
archive:
  filename: ./archive.csv
  type: cvs
logging:
  filename: ./pktservice.log
  timestamp: 2006-01-02 15:04:05.000


