service:
  name: pktservice
  network:
    - channel:
        name: Service1
        tyüe: TC
        recon_interval: 1000
        listener: 
          name: ServerSrv1
          host: 127.0.0.1
          port: 32100
        dialer:
          name: ClientSrv1
          host: 127.0.0.1
          port: 33100    
packet:
  filename: ./sendlist.txt
  wait: 5000
archive:
  filename: ./archive.csv
  type: cvs
logging:
  filename: ./pktservice.log
  timestamp: 2006-01-02 15:04:05.000


